[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm install", "cd client && npm install", "cd server && npm install"]

[phases.build]
cmds = ["cd client && npm run build", "cd server && npm run build"]

[start]
cmd = "npm start"
